language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies (mock & nose are already installed)
install:
  - pip install .
  - pip install pylint
# command to run tests
script: python setup.py test
after_success:
  - pylint --rcfile=.pylintrc simple_salesforce
# turn off email notifications
notifications:
  email: false
