language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
# command to install dependencies (mock & nose are already installed)
install:
  - pip install tox
# command to run tests
script: tox
matrix:
  fast_finish: true
  allow_failures:
    # 2.6, 3.2, 3.3, and 3.4 are no longer supported
    - python: "3.4"
    - python: "3.3"
    - python: "3.2"
    - python: "2.6"
# turn off email notifications
notifications:
  email: false
deploy:
  # Allow travis-ci to deploy new tags to PyPI
  provider: pypi
  user: simple-salesforce
  password:
    secure: "It5A1Ulbsm7tWyrBB7aetdYAYNRr82q91M5nN5Avc6udYTQrOReXufrBOEXtYr4QoS9llF8Rs1NZ9Gz4zheaqUo2Q0+pBzgr2cqy9MgDDj6ok0/k3rehFmABlYmJSBOHZvgG4Lv1Wycfb944Rr1YeUO2HwpdPmaDd54YnKJz0IymgFQJNmy6RtwzhVBzpKMVJIFLYmiDJ0y36JpTj76C/+WUz018yij3VZOV68Qn/4I4k4r0CpkzurchknqqbWSGdUbJZXr7h595hGVomqHqCg7+bEDd5SAD8RgwZCZN4kwNiegLWPq3I48H7WcHmfu3/v3j4dRAXoNL4WJY7MMHuPNGUfMkGGUqyXODF9cZxq4bVanAGu5Sdse3NqG28Pfvy4uuV2JzEdva8vEo+mPiz/hZiEeJoRLK1sS7inZBxjDzdWdiS2SY1wyQbtXZ4wwkpY26dUM/iMN9q1PXOf6K9uHfS5zYJA9WZ/01jnknwmqxqtXFtOrc4dU6t4EWOSJ1UR/XvCxBQ5QFoQtGu6nXMhbCCGpLUz/hi0is9VmPPFkV4skBiF3oRw4IB5w/iD/2kBV3ptIKx2eiCY8G3PRlpCd6/wzV0P3fx5zGUoz2Hnt2zGFUhgKCyoW+OQmwUt0VrsTto6bBCm1LTNkW4a3P0fn4tVQJytSftSg93ikNgz0="
    #secure: "J7qjXx9tmsjZQIyLMRK3roEV1+6GmmME34UrdomlipNixc5MELQLZP2gUThIOf3++824AGX9Dgkq0h5YyAwnawXq7QQFcsOOcz8evcE9v6nVc7EEKCOvIeZ7dXHTAk1a+nLH4I7S5t4B+2bpLI5W3AyHxdpD8TrbZ28tFtuQ2e4="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    repo: simple-salesforce/simple-salesforce
env:
  - TOXENV=unit
  - TOXENV=static
